### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by prodderman** [pyrocoder/toxiin#10]
Не понятно, почему вместо того, что бы просто установить air-datepicker, ты скопировал все исходники?

**Comment by pyrocoder** [comment]
Думаю я сделал это чтобы объединить custom-стили, которые я наложил поверх оригинальных, а также модифицирующий (адаптирующий под проект) код в одном месте.

Согласен с Вами, это не совсем верно, исправлю

**Comment by prodderman** [comment]
Нет, так не годится. Я же должен видеть то, что ты сделал, а не другие люди + изменять исходники либы это плохая практика. Попробуй разобраться, как можно расширить текущий datepicker, может инициализировать его при открытии и т.д. Или, если либа не удовлетворяет твоим требованиям, то попробуй найти другую

**Comment by pyrocoder** [comment]
> Нет, так не годится. Я же должен видеть то, что ты сделал, а не другие люди + изменять исходники либы это плохая практика. Попробуй разобраться, как можно расширить текущий datepicker, может инициализировать его при открытии и т.д. Или, если либа не удовлетворяет твоим требованиям, то попробуй найти другую

@prodderman, сообразил как сделать, можно проверять результат, спасибо! :)))

**Comment by prodderman** [comment]
Уже лучше, но теперь проблемы возникают, если датапикеров на странице несколько. Так же непонятно почему ты вынес датапикер в plugins. У тебя должен быть самодостаточный блок который содержит контейнер, куда будет рендерится календарь, логика по инициализации и стили.

**Comment by pyrocoder** [comment]
@prodderman 
Исправил!!!

**Comment by prodderman** [comment]
Какие сейчас замечания:
1) Календарь - это все же самостоятельный компонент, сейчас же у тебя контейнеры для календаря расползлись по всему проекту

2) Сама инициализация очень не очевидна и не удобна: Что бы добавить еще один календарь, мне придется пройтись по всему проекту и посмотреть какой айди еще не занят и прочие неудобства из этого вытекающие.

3) Как я уже говорил в ишью про стандарты, именовать классы используемые в js нужно с префиксов js-имя-класса

**Comment by pyrocoder** [comment]
> 3. Как я уже говорил в ишью про стандарты, именовать классы используемые в js нужно с префиксов js-имя-класса

принято

**Comment by prodderman** [comment]
Мы наверно не поняли друг друга про префиксы, тут имеется ввиду классы которые в pug.
div.js-block.block: ".js-block" используется для поиска элемента в js, а ".block" используется для стилизации в css. В js же классы именуются с большой буквы: class Calendar

**Comment by pyrocoder** [comment]
> Мы наверно не поняли друг друга про префиксы, тут имеется ввиду классы которые в pug.
> div.js-block.block: ".js-block" используется для поиска элемента в js, а ".block" используется для стилизации в css. В js же классы именуются с большой буквы: class Calendar

@prodderman 
переименовал все кла`ссы - можно проверять

**Comment by prodderman** [comment]
Что то классы как были так и остались. Вижу только в pug добавился .js-datepicker-range, но ты этот класс не используешь для поиска в js

**Comment by prodderman** [comment]
Не понятно также зачем ты скопировал все стили из либы, у тебя ведь уже есть `import 'air-datepicker/dist/css/datepicker.min.css'`

**Comment by prodderman** [comment]
Сейчас очень тяжело воспринимается компонент:
- Он разбит на странные директории (calendar--double и т.п.), где нужны только pug файлы, и лишние js файлы, которые подключают только стили, которые можно описать calendar.scss, и даже пустые файлы стилей.

- Тяжело воспринимается конструктор класса. Имеет смысл вынести инициализацию каждого типа календаря в методы класса, а в конструкторе их просто вызывать.

- У тебя все еще не решена проблема того, что на странице календарей одного типа может быть несколько.

- Так же непонятно у тебя раскиданы импорты для календаря. Очевиднее будет, если все импорты относящиеся к календарю буду лежать в календаре.

**Comment by pyrocoder** [comment]
в работе

**Comment by pyrocoder** [comment]
> * У тебя все еще не решена проблема того, что на странице календарей одного типа может быть несколько.

@prodderman
Решена - я только что проверил на странице с карточками. Остальное в работе.

**Comment by pyrocoder** [comment]
> * Он разбит на странные директории (calendar--double и т.п.), где нужны только pug файлы, и лишние js файлы, которые подключают только стили, которые можно описать calendar.scss, и даже пустые файлы стилей.

исправил

**Comment by pyrocoder** [comment]
> Что то классы как были так и остались. Вижу только в pug добавился .js-datepicker-range, но ты этот класс не используешь для поиска в js

![image](https://user-images.githubusercontent.com/49208398/85234052-87909800-b413-11ea-8a35-211b8e627fa5.png)

Использую, вот скрин, а другого нет, поэтому другие классы не именовал в Pug. А те классы, которые использую в js, в Pug не определены, а зашиты в код плагина в Node Modules.
