### ISSUE TITLE
Компоненты

### ISSUE THREAD

**Issue by prodderman** [pyrocoder/toxiin#11]
Начнем с radio-button:
Во-первых у тебя это не радио-копка, а группа кнопок

Во-вторых очень специфичный компонент, по-хорошему нужно сделать возможным передавать в миксин текст лейбла и начальное состояние.

В-третьих в идеале структура компонента должна быть такая:
.pug
```
mixin block-name
    .block-name
        .block-name__element
        .block-name__element.block-name__element--modifier
```
У тебя же очень часто встречаются элементы без блоков, или модификаторы отдельно от всего.

.scss
```
.block-name {
    &__element {
        &--modifier {
             // styles
        }
    }
}
```
Так же ты используешь препроцессор, но используешь его не правильно. Прочитай доку по scss.

.js
какая то логика, если нужна

Пройдись по проекту и все проверь, это касается всех компонентов

**Comment by prodderman** [comment]
text-input:

у тебя здесь почему то сразу три миксина.
Во-первых, миксин text-input--with-arrow можно решить модификатором. с text-input--date аналогично.

Во-вторых, у тебя нет имени блока, сразу идут элементы.

P.S. Если обобщение миксина только его усложняет, то наверно есть смысл разбить такой миксин на несколько компонентов. Например сделать два блока: text-input и date-input. Это к твоему сведению, у тебя же все решается модификаторами.

**Comment by pyrocoder** [comment]
Принял в работу, спасибо!

**Comment by pyrocoder** [comment]
@prodderman 
 **text-input, radio-button исправил, также прошелся по проекту и внес аналогичные правки, где требовалось**
По scss когда рефакторил, было удобнее полностью писать имя элемента, поэтому не везде использовал сокращения.  Также, когда настраивал новую сборку, я переносил все стили из SASS путем переноса сначала в CSS,  а потом уже в SCSS (по-другому не получилось) - так что они прошли долгий путь :)))

**Comment by prodderman** [comment]
А что поменялось то с radio-button? Ты по-сути просто переименовал в twin-radio-buttons. Тут ясно же что радио кнопка это отдельный компонент

**Comment by prodderman** [comment]
bullet-list:
1) так же очень специфичный, есть смысл передавать массив элементов, а внурти миксина уже рендерить элементы списка основываясь на массиве (пример в [доке](https://pugjs.org/language/iteration.html)).
2) Стилизация идет по тегам (что в стандартах не рекомендуется, еще раз перечитай стандарты)

**Comment by prodderman** [comment]
like-button:
1) Ты используешь примесь, прочитай [пятый пункт](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/bem.md)

2) Это отдельный компонент, почему он определен в компоненте comment?

**Comment by prodderman** [comment]
comment:
1. Так же используется примесь
1. [Почитай](https://github.com/fullstack-development/front-end-best-practices/blob/089733bb862a99358c075458f931eb91823df0fd/HTML/semantic.md) пункт 7 про <br

**Comment by prodderman** [comment]
И вообще не особо понятно разделение на page-elements и ui-elements, в чем логика?

**Comment by pyrocoder** [comment]
> И вообще не особо понятно разделение на page-elements и ui-elements, в чем логика?
просто хотел как-то отделить UI компоненты от компонентов верстки для страниц (комментарий - непосредственный элемент страницы), а UI - компоненты - это что-то более мелкое - у меня логика была такая. Не хотелось все в одну кучу сваливать, чтобы потом сложно было искать в одном длинном списке компонентов что-то. Если это критично, то исправлю

**Comment by pyrocoder** [comment]
> .js
> какая то логика, если нужна

видимо здесь предполагалась картинка с кодом, как нужно оформлять названия классов, но она не отобразилась, в стандартах пока этого не нашел - буду от начала и до конца пересматривать их

**Comment by prodderman** [comment]
bullet-list уже лучше.
- Странно, что можно передать только три значения, из которых формируется массив. Что если понадобится больше элементов? + непонятные имена параметров (val1, val2).

- Непонятный [селектор](https://github.com/pyrocoder/toxiin/blob/30f831771c88d75ebc92e15d42905066bb261eb5/src/components/ui-elements/bullet-list/bullet-list.scss#L17-L26), зачем first-child? и зачем display: flex?

**Comment by prodderman** [comment]
button.
- непонятное название элемента: filter-white
- у тебя стилизация картинки по тегу, хотя есть класс
- странное использование кнопки, тебе всегда требуется передавать второй аргумент?

**Comment by pyrocoder** [comment]
увидел, приступил

**Comment by pyrocoder** [comment]
@prodderman по всем пунктам исправил, стрелку перенес во wrapper

**Comment by prodderman** [comment]
В bullet-list ничего не исправил https://github.com/pyrocoder/toxiin/issues/11#issuecomment-644270131

**Comment by prodderman** [comment]
По button, не понятно зачем ты вынес оттуда иконку стрелки и сделал какую то обертку. Этим как минимум неудобно пользоваться. Иконка - это элемент кнопки, и логичнее было организовать кнопку так, чтобы она сама отображала стрелку в зависимости от некого условия. Так же все состояния кнопки (неактивная или закрашенная) так же должны быть описаны в кнопке. В итоге у тебя должен быть описан понятный интерфейс, что кнопка принимает: текст, нужно отображать иконку или нет, закрашена или нет и т.д.

**Comment by pyrocoder** [comment]
> bullet-list уже лучше.
> * Странно, что можно передать только три значения, из которых формируется массив. Что если понадобится больше элементов? + непонятные имена параметров (val1, val2).
> * Непонятный [селектор](https://github.com/pyrocoder/toxiin/blob/30f831771c88d75ebc92e15d42905066bb261eb5/src/components/ui-elements/bullet-list/bullet-list.scss#L17-L26), зачем first-child? и зачем display: flex?
> В bullet-list ничего не исправил [#11 (comment)](https://github.com/pyrocoder/toxiin/issues/11#issuecomment-644270131)

Исправил.

**Comment by prodderman** [comment]
bullet-list хорошо. А кнопку не исправил

**Comment by pyrocoder** [comment]
> bullet-list хорошо. А кнопку не исправил

исправил через кастомные атрибуты

**Comment by prodderman** [comment]
Зачем через js? тебе достаточно использовать модификаторы для всех состояний

**Comment by pyrocoder** [comment]
> Зачем через js в кнопке? тебе достаточно использовать модификаторы для всех состояний


@prodderman 
Не совсем понял как оформлять, т.к. в случае добавления модификатора получается примесь, а примеси добавлять нельзя по стандартам. Как правильно офрмлять через модификатор?
