### ISSUE TITLE
Like Button

### ISSUE THREAD

**Issue by prodderman** [pyrocoder/toxiin#13]
- Классы с префиксом js- используются для тогда чтобы найти элемент на странице в js, у тебя же они используются для стилизации. Если тебе нужно добавить из js модификатор activated, то ты и добавляй like-button--activated

- Блок не должен знать об окружении, следовательно не может обращаться к элементам внешних блоков (.js-card__like-button).

- В конструкторе лучше не держать много логики. У тебя есть функции, которые можно спокойной вынести в методы.

- Странное поведение этого компонента, у тебя получается это счетчик кликов, а не кнопка лайка. Обычно при клике ставится лайк, а при повторном нажатии - убирается

**Comment by pyrocoder** [comment]
Все пункты исправил

**Comment by prodderman** [comment]
А зачем .js-like-button__icon и .js-like-button__counter оставил, если не используешь их?

lb.firstElementChild.src='./assets/img/favorite-24px.svg' для чего?

Опять же не используешь возможности препроцессора, проверяй сразу во всех компонентах

**Comment by pyrocoder** [comment]
> А зачем .js-like-button__icon и .js-like-button__counter оставил, если не используешь их?
> lb.firstElementChild.src='./assets/img/favorite-24px.svg' для чего?
> Опять же не используешь возможности препроцессора, проверяй сразу во всех компонентах

По всем пунктам исправил.

**Comment by pyrocoder** [comment]
> А зачем .js-like-button__icon и .js-like-button__counter оставил, если не используешь их?


> lb.firstElementChild.src='./assets/img/favorite-24px.svg' для чего?

убрал

> Опять же не используешь возможности препроцессора, проверяй сразу во всех компонентах

По всем пунктам исправил.

**Comment by pyrocoder** [comment]
> А зачем .js-like-button__icon и .js-like-button__counter оставил, если не используешь их?

убрал

> lb.firstElementChild.src='./assets/img/favorite-24px.svg' для чего?

убрал

> Опять же не используешь возможности препроцессора, проверяй сразу во всех компонентах

Не знал, что нужно обязательно использовать. Здесь исправил, также пройдусь по проекту.

**Comment by prodderman** [comment]
- В pug есть неиспользуемый параметр.

- Проверь в файле стилей есть неиспользуемые стили

**Comment by pyrocoder** [comment]
> * В pug есть неиспользуемый параметр.

убрал

**Comment by a-poluhin** [comment]
Можно закрывать
