### ISSUE TITLE
Dropdown

### ISSUE THREAD

**Issue by prodderman** [pyrocoder/toxiin#14]
- dropdown--short не имеет смысла, так как это легко решается дополнительным аргументом, а сейчас у тебя почти полная копипаста обычного дропдауна

- Конструктор очень тяжелый, у тебя все функции можно вынести в методы.

- calc-item по-сути не имеет смысла в отрыве от дропдауна. Он сделан отдельным блоком, и то что дропдаун обращается к внутренностям calc-item, нарушает самодостаточность этого блока

**Comment by pyrocoder** [comment]
в работе

**Comment by pyrocoder** [comment]
> * Конструктор очень тяжелый, у тебя все функции можно вынести в методы.
вынес все из конструктора в отдельный метод

**Comment by pyrocoder** [comment]
> * dropdown--short не имеет смысла, так как это легко решается дополнительным аргументом, а сейчас у тебя почти полная копипаста обычного дропдауна

убрал

**Comment by pyrocoder** [comment]
> * dropdown--short не имеет смысла, так как это легко решается дополнительным аргументом, а сейчас у тебя почти полная копипаста обычного дропдауна

убрал, аргумент добавил

> * Конструктор очень тяжелый, у тебя все функции можно вынести в методы.

вынес все из конструктора в отдельный метод

> * calc-item по-сути не имеет смысла в отрыве от дропдауна. Он сделан отдельным блоком, и то что дропдаун обращается к внутренностям calc-item, нарушает самодостаточность этого блока

убрал лишний блок, заменил его на принадлежность к dropdown

**Comment by prodderman** [comment]
Так не пойдет, ты по-сути вынес всю логику из конструктора и вынес в метод, сложность при этом никуда не делась. Тебе стоит продумать логику дропдауна, что бы каждая функция была понятна и выполняла ровно одну задачу: например функция, которая ответственна за открытие/закрытия, другая ищет каунтеры и навешивает на них обработчики и т.д.

Так зачем то заюзал примесь, хотя нужно было добавить аргумент. 

Плюс дропдаун у тебя опять получился слишком специфичный, лэйблы для каунтеров и плейсхолдер, а также количество каунтеров стоит также передавать через аргументы, а не менять неочевидным способом через js

**Comment by pyrocoder** [comment]
@prodderman 
Прошелся по плагину, разобрал его логические на компоненты, и затем собрал заново. Удалось несколько упростить структуру. Класс сделал функцией, так как он здесь не нужен
