### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by prodderman** [pyrocoder/toxiin#16]
- Не используешь возможности препроцессора в стилях

- Есть селекторы по тегам

- Есть миксы, в стандартах есть пункт по этому поводу

**Comment by pyrocoder** [comment]
> * Не используешь возможности препроцессора в стилях
> * Есть селекторы по тегам
исправил

**Comment by pyrocoder** [comment]
> * Не используешь возможности препроцессора в стилях
> * Есть селекторы по тегам
> * Есть миксы, в стандартах есть пункт по этому поводу

@prodderman исправил, примесь убрал

**Comment by prodderman** [comment]
Уже лучше, убери лишнии комментарии в стилях и сравни с макетов, у тебя фичи теперь разъехались

**Comment by pyrocoder** [comment]
> Уже лучше, убери лишнии комментарии в стилях и сравни с макетов, у тебя фичи теперь разъехались

готово

**Comment by prodderman** [comment]
- featureType не понятное имя, это же иконка, а не тип.

- descr - тоже непонятное сокращение: description

- У блока есть внешнее позиционирование, что противоречит принципам БЭМ. Позиционированием блоков должны заниматься родительские блоки.

**Comment by pyrocoder** [comment]
> * featureType не понятное имя, это же иконка, а не тип.
> * descr - тоже непонятное сокращение: description

исправил
