### ISSUE TITLE
Expandable Checkbox List

### ISSUE THREAD

**Issue by prodderman** [pyrocoder/toxiin#18]
- Это не дропдаун, предполагалось, что он будет раскрываться, толкая контент снизу

- Не понятно, что происходит в expandable-checkbox-list.js. Мне кажется там логика не относящаяся к списку чекбоксов

- Мешанина в стилях, много стилей, которые не относятся к списку чекбоксов

- Компонент очень специфичен, есть смысл добавить возможность передавать нужный массив элементов снаружи

**Comment by pyrocoder** [comment]
> * Это не дропдаун, предполагалось, что он будет раскрываться, толкая контент снизу
> * Не понятно, что происходит в expandable-checkbox-list.js. Мне кажется там логика не относящаяся к списку чекбоксов
> * Мешанина в стилях, много стилей, которые не относятся к списку чекбоксов
> * Компонент очень специфичен, есть смысл добавить возможность передавать нужный массив элементов снаружи

исправил, массив добавлю

**Comment by prodderman** [comment]
Почему теперь у тебя используются классы из другого блока (checkbox-container)? Либо переиспользуй его полностью, либо делай элементом checkbox-list.

Есть примесь openOrNot, которая по-сути булево значение, в зависимости от которого блок сам должен добавлять класс.

P.S. checkbox это элемент формы, а у всех элементов формы желательно указывать имя

**Comment by pyrocoder** [comment]
> Почему теперь у тебя используются классы из другого блока (checkbox-container)? Либо переиспользуй его полностью, либо делай элементом checkbox-list.
> 
> Есть примесь openOrNot, которая по-сути булево значение, в зависимости от которого блок сам должен добавлять класс.
> 
> P.S. checkbox это элемент формы, а у всех элементов формы желательно указывать имя

готово

**Comment by pyrocoder** [comment]
> Есть примесь openOrNot, которая по-сути булево значение, в зависимости от которого блок сам должен добавлять класс.

@prodderman 
Не совсем понял как оформлять, т.к. в случае добавления модификатора получается примесь, а примеси добавлять нельзя по стандартам. Как правильно офрмлять через модификатор?
