### ISSUE TITLE
Ненужные файлы

### ISSUE THREAD

**Issue by prodderman** [pyrocoder/toxiin#5]
Проверь temp и libs. большую часть зависимостей, если даже не все, можно установить через npm и не засорять репозиторий. Возможно некоторые даже не используются. Это так же касается стилей bootstrap. Также стоит в .gitignore занести локальные настройки редактора.

**Comment by pyrocoder** [comment]
Переподключил все плагины/библиотеки согласно инструкций выше. Лишние файлы почистил. Спасибо!

**Comment by prodderman** [comment]
![image](https://user-images.githubusercontent.com/24736776/82246709-60a3f980-996f-11ea-943d-68221c7f15ef.png)
Почему у тебя рядом со страницами лежат скомпилированные дубликаты? они должны лежать в dist.

**Comment by pyrocoder** [comment]
это не специально сделано: редактор иногда сам по себе включал встроенные watcher-ы,  я их отключал, но они иногда включались обратно без моего участия, подчищу лишние html

**Comment by pyrocoder** [comment]
убрал лишние файлы
