### ISSUE TITLE
Настроить сборку

### ISSUE THREAD

**Issue by prodderman** [pyrocoder/toxiin#6]
Настрой сборку так, чтобы все необходимое для запуска лежало в бандле, например сейчас у тебя весь .pug нужно компилть отдельно. 
Грубо говоря, что бы я смог взять твой бандл отдельно от всего проекта, запустить, и все должно отображаться корректно.

**Comment by pyrocoder** [comment]
Настроил сборку и пересобрал проект для продакшен. Все страницы и необходимые файлы выкладываются в dist и оттуда запускаются не вовлекая source-файлы.
Дополнительно создал INDEX страницу со ссылками на страницы.

**Comment by prodderman** [comment]
Все равно не понимаю как работает у тебя сборка. В dev режиме, если я что то меняю в проекте, то изменения не подхватываются. Получается мне нужно всегда сначала запускать npm run build, а только потом dev. Это как минимум не удобно. Вопрос, для чего тогда дев сборка? Сделай так, что бы удобно было разрабатывать, что бы билд пересобирался при любом изменении в проекте.

**Comment by pyrocoder** [comment]
я тоже не понял, откуда это взялось, буду разбираться

**Comment by pyrocoder** [comment]
@prodderman разобрался в чем дело: сборка требовала полную копию всех файлов с помощью copyWebpackPlugin - донастроил его,  и теперь девелопмент-режим работает как надо!

**Comment by prodderman** [comment]
Сейчас уже лучше, webpack-dev-server по сути сам копирует в память все файлы сборки. Тут нужно, что бы директория, на которой запущен сервер, содержала скомпилированные страницы, что достигается с помощью html-webpack-harddisk-plugin. Но это уже на твое усмотрение. Закрываю ишью
