### ISSUE TITLE
Perfect pixel

### ISSUE THREAD

**Issue by prodderman** [pyrocoder/toxiin#7]
Есть довольно серьезные различия с макетом. Проверь все еще раз по perfect pixel.

**Comment by pyrocoder** [comment]
1. **Оформил Index-страницу со ссылками** на основные страницы задания.
2. **Посадил страницы colors & styles, form-elements и cards на оформление UI Kit**
3. **Переработал оформление карточки** **комнаты**: оформил dots карточки с комнатами под дизайн макета, скорректировал шрифты оформления
4. **Rate-Button, Like-Button****: обновил внешний вид** (заменил иконки), а также переписал js, каждой кнопке задал уникальный #id, проверил функционал
5. Проверил работу (отступы) выпадающих списков, высоту registration page (ранее было 684px, теперь. 706px), скорректировал высоту карточки регистрации, уменьшил длину border-bottom в блоке features, скорректировал отступ количества отзывов посетителей номера в room-details, проверил отступ между заглавием текстовой формы и самой формой карточек

**Comment by pyrocoder** [comment]
@prodderman Степан, проверьте, пожалуйста, результаты

**Comment by prodderman** [comment]
![image](https://user-images.githubusercontent.com/24736776/82762770-1a4a1100-9e2d-11ea-9446-75c63921adb8.png)

![image](https://user-images.githubusercontent.com/24736776/82762778-246c0f80-9e2d-11ea-9330-ddae8fc25df5.png)

все еще есть значительные расхождения

**Comment by prodderman** [comment]
проверяй, пожалуйста, все элементы

**Comment by pyrocoder** [comment]
@prodderman , здравствуйте! Исправил. В прошлый раз я не обновил папку dist после последних изменений

**Comment by pyrocoder** [comment]
@prodderman
Степан, здравствуйте!
Я переписал **dropdown**, имеет смысл взглянуть:
https://pyrocoder.github.io/toxiin/dist/form-elements.html

**Comment by prodderman** [comment]
Твоя карточка:
![image](https://user-images.githubusercontent.com/24736776/83441561-eb591e00-a470-11ea-9b51-6d8927891c61.png)

В макете:
![image](https://user-images.githubusercontent.com/24736776/83441457-c5337e00-a470-11ea-95cd-1f8af71c4d48.png)

Есть различия, особенно скругленные углы. Еще раз повторю, проверяй все компоненты сам

**Comment by pyrocoder** [comment]
![Uploading Screenshot 2020-06-03 at 00.39.08.png…]()
Цвет звезды подправил. Размер шрифта № отеля уменьшил до 21 пх (в макете он указан неявно - приходится подбирать путем накладывания полупрозрачного пиксел-перфект экрана.
border-radius: 4px у меня выставлен, но, оказывается, не подействовал
Насчет белых стрелок по бокам - в макете на первой фотке галереи они есть, на остальных нет - ошибка макета -оставляю их, т.к считаю логичным их иметь, т.к точки отвечают больше за индикацию, на какой фотке мы сейчас находимся

**Comment by prodderman** [comment]
Выглядит хорошо, закрываю

**Comment by pyrocoder** [comment]
> Выглядит хорошо, закрываю

классно, спасибо! сори что не с первого раза
