### ISSUE TITLE
Стандарты

### ISSUE THREAD

**Issue by prodderman** [pyrocoder/toxiin#8]
Пройдись по [стандартам](https://github.com/fullstack-development/front-end-best-practices) и еще раз проверь. Особенно обрати внимание на разделы БЭМ, JQuery и семантика.

**Comment by pyrocoder** [comment]
Нашел и **исправил ошибку в .header**, где неправильно использованы модификаторы (через двойной дефис).

**Comment by pyrocoder** [comment]
@prodderman Степан, проверьте плз данный issue

**Comment by prodderman** [comment]
По проекту часто втречается [использование id](https://github.com/fullstack-development/front-end-best-practices/blob/28389de90a81e4c51636b7786bdfcb082cafe18a/HTML/tags.md) (пункт 10).
Пройдись еще раз по стандартам и все внимательно проверь.

**Comment by pyrocoder** [comment]
id убрал (like-button, rate-button)

**Comment by prodderman** [comment]
Все еще наблюдаю айдишники в проекте)

Так же придерживайся единому стилю. если используешь одинарные ковычки, то используй их везде, если используешь отступ в два пробела, то используй такой отступ везде и т.д.

**Comment by pyrocoder** [comment]
по айдишникам в хедере (дропдаун) исправил, в проекте проверю, кавычки в работе. По отступам стараюсь так и использовать 2 пробела (мигрировал с четырех пробелов так как не хватало ширины экрана)

**Comment by pyrocoder** [comment]
@prodderman
По #id проверил - больше нигде нет кроме jquery-UI-slider (там не убрать). 
Ковычки привел к единообразию.
Отступы проверил.

**Comment by prodderman** [comment]
Уверен, что нельзя избавиться от айди в слайдере? Я вижу что можно. Плюс, у тебя возникнет проблема с уникальностью айди, если слайдеров на странице будет несколько

**Comment by pyrocoder** [comment]
Со второго раза получилось избавиться - я просто переименовал id в class (в прошлый раз делал так же - видимо что-то не сработало)
