### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by prodderman** [pyrocoder/toxiin#9]
![code](https://user-images.githubusercontent.com/24736776/82247225-3e5eab80-9970-11ea-8620-eee780e0cb4c.png)
Во первых:
Странные названия для миксинов. По-хорошему название миксина должно совпадать с названием файла. Это удобно при импорте таких миксинов, так как ты знаешь название файла, а следовательно знаешь название миксина.

Во-вторых:
Миксины слишком специфичны, и по-сути у тебя тут (на скриншоте) дублируется большая часть миксина. Такие миксины нужно обобщить, передавая имя, дату и текст.

В-третьих:
Блок должен быть самодостаточным и не знать о внешнем мире. У тебя почему то в блоке comment появляется элементы блока room-detail и card, что нарушает принципы БЭМ.

В-четвертых:
Названия блоков БЭМ тоже странные. Названия должны быть осознанными и понятными, передавать смысл блока. Например, я не понимаю что такое .col100, это колонка шириной в 100px? но в стилях она width: 100%. Плюс это глобальные классы, которые нарушают принципы БЭМ.

PS. Это относится ко всем блокам. Проверь по всему проекту

**Comment by pyrocoder** [comment]
действительно, много id в одном плагине, и миксин этот я вспомнил,  пройдусь по проекту проверю

**Comment by pyrocoder** [comment]
1.**Переписал миксины, проверил на самодостаточность:**
  like-button
  rate-button
  card--room
  comment
  feature и пр.
2. **Убрал глобальные классы, проверил названия.**
3. **Оптимизировал структуру папок компонентов**

@prodderman Степан, думаю, имеет смысл взглянуть.

**Comment by prodderman** [comment]
Не везде убрал глобальные классы, например в header все еще присутствуют .container и .row. (Проверяй сразу везде)

Так же проверь везде модификаторы, например в том же header 
`a.header__menu-link.active,` где модификатор active не по БЭМ 
должен быть `a.header__menu-link..header__menu-link--active`

**Comment by pyrocoder** [comment]
модификаторы в header исправил, глобальные классы в работе, по проекту проверю

**Comment by pyrocoder** [comment]
@prodderman **.container** и **.row** у меня подвязаны к бутстрап-сетке. 
Пока не совсем понял, как правильнее совместить БЕМ и бутстрап (в интернете версии у людей разные, но читал, что компании используют, а оформляют по-разному). Наверное, в текущем проекте правильнее всего установить свою сетку и назвать по БЕМ (но стили будут одинаковые - только названия элементов разные на каждой странице, где они используются)

**Comment by pyrocoder** [comment]
@prodderman сетку сделал на jquery, перенастроил адаптивность, глобальные классы убрал (теперь точно)

**Comment by prodderman** [comment]
А зачем тебе бутстрап? как я уже говорил глобальные классы нарушают самодостаточность блоков, плюс хотелось бы видеть как ты сам что либо делаешь. 

Я в все еще наблюдаю глобальные классы и стили в src/scss. Если это стили для страниц, так и держи эти стили на одном уровне с страницами. Страницы по-сути те же компоненты.

**Comment by pyrocoder** [comment]
> А зачем тебе бутстрап? как я уже говорил глобальные классы нарушают самодостаточность блоков, плюс хотелось бы видеть как ты сам что либо делаешь.
> 
> Я все еще наблюдаю глобальные классы и стили в src/scss. Если это стили для страниц, так и держи эти стили на одном уровне с страницами. Страницы по-сути те же компоненты.

h1,h2,h3 - исправил.
Подчистил оставшиеся стили (они не использовались, но действительно висели кое-где. 
Вынес единственно-оставшиеся стили в стили секций страниц (файл pages.scss)
Надеюсь, так будет верно.

**Comment by pyrocoder** [comment]
Вот в таком виде получилось:

html {
  box-sizing: border-box;
  font-size: 14px;
  line-height: 24px;
  font-family: 'Montserrat-Regular', serif;
  font-style: normal;
  font-weight: normal;
  color: rgba(31, 32, 65, 0.75);
}

// pages' styles

.header,
.footer,
.cards,
.colors-and-types,
.form-elements,
.landing,
.login,
.reg,
.room-details,
.search-room {

  * {
    box-sizing: inherit;
    outline: none;
    &::before {
      box-sizing: inherit;
      font-size: 14px;
      outline: none;
    }
    &::after {
      box-sizing: inherit;
      font-size: 14px;
      outline: none;
    }
    &::placeholder {
      color: $gray;
      &:hover, &:focus {
        color: $dark-gray;
      }
    }
  }
  img {
    max-width: 100%;
    height: auto;
  }
  a {
    outline: none;
    &:hover {
      text-decoration: none;
      cursor: pointer;
    }
  }
  li { list-style-type: none; }
